name: skysat_stereo_snow
channels:
 - conda-forge
dependencies:
 # core data science
 - python
 - scipy
 - numpy
 - pandas
 - matplotlib
 - ipykernel
 # geospatial (raster+vector)
 - gdal
 - rasterio
 - geopandas
 - pygeos
 - shapely
 - contextily
 - descartes
 - rioxarray
 - xarray
 - xdem
 # reference DEM querying
 - earthengine-api
 - geedim
 # misc
 - pip
 - psutil
 - seaborn
 - pip:
   # rotation_matrices
   - pyquaternion
   # misc
   - p_tqdm
   # geospatial+plotting
   - "--editable=git+https://github.com/dshean/pygeotools.git#egg=pygeotools"
   - "--editable=git+https://github.com/dshean/demcoreg.git#egg=demcoreg"
   - "--editable=git+https://github.com/ShashankBice/imview.git@isprs_version#egg=imview"
   - "--editable=git+https://github.com/cmla/rpcm.git#egg=rpcm"
   # Sx calculation
   - topo-descriptors
   # needed for xdem ICP coregistration
   - opencv-python
