name: skysat_stereo_snow
channels:
 - defaults
 - conda-forge
dependencies:
 # core data science
 - python=3.13
 - scipy
 - numpy
 - pandas
 - matplotlib
 - ipykernel
 # geospatial (raster+vector)
 - gdal
 - geopandas
 - rioxarray
 - xarray
 - xdem
 # reference DEM querying
 - earthengine-api
 - geedim
 # misc
 - pip
 - psutil
 - seaborn
 - pip:
   # parallel job running
   - p_tqdm
   # Sx calculation
   - topo-descriptors
   # needed for xDEM ICP coregistration
   - pytransform3d
   - opencv-python
